name: pub_mirror
description: A multi-thread tool to download content from Pub. Then the result can be served by a http server and taken as the backend of pub, flutter or even Pub Mirror itself.
version: 1.0.3
homepage: https://github.com/huiyiqun/pub-mirror
author: Hui Yiqun <i@huiyiqun.me>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  pub_client: ^3.0.3
  executor: ^2.1.2
  path: ^1.6.2
  args: ^1.5.1
  http: ^0.11.3+17
  pedantic: ^1.4.0
  quiver_log: ^1.0.6
  logging: ^0.11.3+2

dev_dependencies:
  pedantic: ^1.4.0

executables:
  pub_mirror:
